/**
 * Bundle all src/ modules into a single file for browser use.
 *
 * The modules are concatenated in dependency order. Each module uses
 * the UMD pattern: in Node (tests), they export via module.exports;
 * in the browser (Qualtrics), they create window globals.
 *
 * Run: npm run build
 * Output: dist/qualtrics-mapping.js
 */

var fs = require("fs");
var path = require("path");

// Order matters: modules with no dependencies first, then modules
// that reference globals created by earlier modules.
var modules = [
  "src/coordinates.js",
  "src/randomization.js",
  "src/i18n.js",
  "src/layout.js",
  "src/geocode.js",
  "src/overlays.js",
  "src/drawing.js",
  "src/display.js",
  "src/qualtrics-integration.js",
];

var header = [
  "/**",
  " * QualtricsMapping -- interactive map drawing for Qualtrics surveys",
  " * https://github.com/bowers-illinois-edu/QualtricsMapping",
  " * License: GPL-3.0",
  " *",
  " * This file is auto-generated by build.js. Do not edit directly.",
  " * To rebuild: npm run build",
  " */",
  "",
].join("\n");

var distDir = path.join(__dirname, "dist");
if (!fs.existsSync(distDir)) {
  fs.mkdirSync(distDir);
}

var parts = [header];
modules.forEach(function (modulePath) {
  var fullPath = path.join(__dirname, modulePath);
  var source = fs.readFileSync(fullPath, "utf-8");
  parts.push("// --- " + modulePath + " ---");
  parts.push(source);
  parts.push("");
});

var bundle = parts.join("\n");
var outPath = path.join(distDir, "qualtrics-mapping.js");
fs.writeFileSync(outPath, bundle);

console.log("Built " + outPath + " (" + bundle.length + " bytes)");
